repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.5.2
    hooks:
    -   id: autopep8
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.0
    hooks:
    -   id: reorder-python-imports
        args: [--py36-plus]
        exclude: ^install-local.py$
    -   id: reorder-python-imports
        files: install-local.py
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.4.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
        exclude: ^install-local.py$
    -   id: pyupgrade
        files: install-local.py
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v2.0.1
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
    -   id: mypy
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v7.0.0
    hooks:
    -   id: eslint
        args: [--fix]
-   repo: local
    hooks:
    -   id: scss-lint
        name: scss-lint
        entry: scss-lint
        types: [scss]
        language: ruby
        additional_dependencies: ['scss_lint:0.57.0']
    -   id: no-github-dot-git
        name: No need for .git for github/gitlab urls
        entry: '(github|gitlab).*\.git'
        files: all-repos.yaml
        language: pygrep
