repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: debug-statements
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.1
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.3
    hooks:
    -   id: autopep8
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.3.5
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/asottile/pyupgrade
    rev: v1.11.1
    hooks:
    -   id: pyupgrade
        args: [--py36-plus]
        exclude: ^install-local.py$
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.660
    hooks:
    -   id: mypy
        exclude: ^install-local.py$
-   repo: local
    hooks:
    -   id: scss-lint
        name: scss-lint
        entry: scss-lint
        types: [scss]
        language: ruby
        additional_dependencies: ['scss_lint:0.57.0']
    -   id: no-github-dot-git
        name: No need for .git for github urls
        entry: 'github.*\.git'
        files: all-repos.yaml
        language: pygrep
