language: python
python: 3.6
install: pip install virtualenv --upgrade
script: make
after_success: ./push_to_gh.sh
branches:
    except:
        - master
env:
    global:
        # GH_TOKEN
        - secure: nNgNYmtwXquPRuAFi/6kXOVjSYroglxuIjvZHDun5eCYikV1KgvXM1Q9Yh3CWgNmIWG1LKt76nt/5u4tLleJiZ7AbjcmLMb9dw7679jFNaDd14tIGyWyYBzrqfqxnayTNLclcfp59l0Yi3ag1i7z4J94LM+7tp8D4jr7RyLd++I=
sudo: false
cache:
    directories:
        - $HOME/.cache/pip
